**03rd Feb : Binary, mathematical, functional operations in numpy, pandas basict**

In [ ]:
import numpy as np

data = np.array([[1], [2], [3]])

In [ ]:
data.ndim

2

In [ ]:
data

array([[1],
       [2],
       [3]])

In [ ]:
np.squeeze(data)  ## reducing diumension

array([1, 2, 3])

In [ ]:
## it only remove the dimension not the rows and columns

In [ ]:
a = np.squeeze(data)

a

array([1, 2, 3])

In [ ]:
a.ndim

1

In [ ]:
## repeat



In [ ]:
data

array([[1],
       [2],
       [3]])

In [ ]:
np.repeat(data, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [ ]:
#### when we need to increase the number of rows or columns in our image processing times, that time it should be handy.

In [ ]:
b = np.array([[1,2], [3,4]])

In [ ]:
b

array([[1, 2],
       [3, 4]])

In [ ]:
np.repeat(b, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [ ]:
## one thing needs to notice that the repeat value returns the values after flattening it

In [ ]:
np.repeat(b,2 , axis = 1) ## axis 1 so the number of the columns are increased

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [ ]:
np.repeat(b,2 , axis = 0) ## axis = , so the number of rows increased.

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [ ]:
## rotation of the elements of the array

In [ ]:
data

array([[1],
       [2],
       [3]])

In [ ]:
np.roll(data, 1) ## 1 times rotation

array([[3],
       [1],
       [2]])

In [ ]:
np.roll(data, 2) ## 2 times rotation

array([[2],
       [3],
       [1]])

In [ ]:
np.roll(data, -1) ## -1 times rotation

array([[2],
       [3],
       [1]])

In [ ]:
np.diag(np.array([1,2,3,4])) ## placing the elements in diagonal

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
c = np.array([[[1,2], [3,4], [5,6]]])

In [ ]:
c

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [ ]:
np.roll(c, -2)

array([[[3, 4],
        [5, 6],
        [1, 2]]])

In [ ]:
np.roll(c, -2, axis = 0)

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [ ]:
np.roll(c, -2, axis = 1) ## columnwise rotation

array([[[5, 6],
        [1, 2],
        [3, 4]]])

In [ ]:
### binary operation on array

In [ ]:
np.diag(np.array([1,2,3,4,5]))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [ ]:
arr1 = np.random.randint(1,10, (3,4))
arr2 = np.random.randint(1,10, (3,4))

In [ ]:
arr1

array([[4, 7, 2, 3],
       [4, 3, 3, 3],
       [9, 7, 2, 9]])

In [ ]:
arr2

array([[8, 2, 3, 1],
       [5, 3, 4, 1],
       [3, 5, 1, 3]])

In [ ]:
arr1 + arr2 ## indexwise addition

array([[12,  9,  5,  4],
       [ 9,  6,  7,  4],
       [12, 12,  3, 12]])

In [ ]:
arr1 * arr2 ## indexwise multiplication

array([[32, 14,  6,  3],
       [20,  9, 12,  3],
       [27, 35,  2, 27]])

In [ ]:
arr1 / arr2 ## indexwise division

array([[0.5       , 3.5       , 0.66666667, 3.        ],
       [0.8       , 1.        , 0.75      , 3.        ],
       [3.        , 1.4       , 2.        , 3.        ]])

In [ ]:
arr1 > arr2 ## indexwise comparison

array([[False,  True, False,  True],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [ ]:
### Numpy string function

In [ ]:
~arr1

array([[ -5,  -8,  -3,  -4],
       [ -5,  -4,  -4,  -4],
       [-10,  -8,  -3, -10]])

In [ ]:
arr1

array([[4, 7, 2, 3],
       [4, 3, 3, 3],
       [9, 7, 2, 9]])

In [ ]:
arr = np.array(["pw", "skills"])

In [ ]:
arr

array(['pw', 'skills'], dtype='<U6')

In [ ]:
## performing some operation using string functions

In [ ]:
np.char.upper(arr)

array(['PW', 'SKILLS'], dtype='<U6')

In [ ]:
np.char.upper(np.array(["Ajay"]))

array(['AJAY'], dtype='<U4')

In [ ]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [ ]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [ ]:
## Mathemarical Function in numpy

In [ ]:
arr1

array([[4, 7, 2, 3],
       [4, 3, 3, 3],
       [9, 7, 2, 9]])

In [ ]:
np.sin(arr1) ## using sin theta

array([[-0.7568025 ,  0.6569866 ,  0.90929743,  0.14112001],
       [-0.7568025 ,  0.14112001,  0.14112001,  0.14112001],
       [ 0.41211849,  0.6569866 ,  0.90929743,  0.41211849]])

In [ ]:
np.cos(arr1)

array([[-0.65364362,  0.75390225, -0.41614684, -0.9899925 ],
       [-0.65364362, -0.9899925 , -0.9899925 , -0.9899925 ],
       [-0.91113026,  0.75390225, -0.41614684, -0.91113026]])

In [ ]:
np.log10(arr1)

array([[0.60205999, 0.84509804, 0.30103   , 0.47712125],
       [0.60205999, 0.47712125, 0.47712125, 0.47712125],
       [0.95424251, 0.84509804, 0.30103   , 0.95424251]])

In [ ]:
np.exp(arr1)

array([[5.45981500e+01, 1.09663316e+03, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 2.00855369e+01, 2.00855369e+01, 2.00855369e+01],
       [8.10308393e+03, 1.09663316e+03, 7.38905610e+00, 8.10308393e+03]])

In [ ]:
np.power(arr1, 3)

array([[ 64, 343,   8,  27],
       [ 64,  27,  27,  27],
       [729, 343,   8, 729]])

In [ ]:
np.mean(arr1)

4.666666666666667

In [ ]:
np.min(arr1)

2

In [ ]:
np.max(arr1)

9

In [ ]:
np.std(arr1)

2.494438257849294

In [ ]:
arr1 - arr2

array([[-4,  5, -1,  2],
       [-1,  0, -1,  2],
       [ 6,  2,  1,  6]])

In [ ]:
np.subtract(arr1, arr2)

array([[-4,  5, -1,  2],
       [-1,  0, -1,  2],
       [ 6,  2,  1,  6]])

In [ ]:
np.multiply(arr1, arr2)

array([[32, 14,  6,  3],
       [20,  9, 12,  3],
       [27, 35,  2, 27]])

In [ ]:
arr1 * arr2

array([[32, 14,  6,  3],
       [20,  9, 12,  3],
       [27, 35,  2, 27]])

In [ ]:
np.mod(arr1,arr2) ## return element wise remainder

array([[4, 1, 2, 0],
       [4, 0, 3, 0],
       [0, 2, 0, 0]])

In [ ]:
np.sqrt(arr1)

array([[2.        , 2.64575131, 1.41421356, 1.73205081],
       [2.        , 1.73205081, 1.73205081, 1.73205081],
       [3.        , 2.64575131, 1.41421356, 3.        ]])

In [ ]:
arr = np.array([5,6,1,2])

In [ ]:
arr

array([5, 6, 1, 2])

In [ ]:
np.sort(arr)

array([1, 2, 5, 6])

In [ ]:
np.searchsorted(arr,3) ## answer will be telling that in which position we have to enter the value in order to get the sorted array

4

In [ ]:
arr_1 = np.array([0,1,2,3,0,4])

np.count_nonzero(arr_1) ## showing the number of elements having non zero.

4

In [ ]:
arr_1 > 0

array([False,  True,  True,  True, False,  True])

In [ ]:
## knowing the index

np.where(arr_1>0)

(array([1, 2, 3, 5]),)

In [ ]:
## if you want the data where it satisfy the condition // Extract the data from the array excluding the zeros

np.extract(arr_1>0, arr_1)

array([1, 2, 3, 4])

In [ ]:
np.searchsorted(arr_1, 7)

6

In [ ]:
## matrix >> 2D array

In [ ]:
import numpy.matlib as nm ## a library in which we direct operate with matrix

In [ ]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [ ]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

***NUMPY LINEAR ALGEBRA***

In [88]:
arr1 = np.array([[1,3], [7,8]])
arr2 = np.array([[2,3], [4,5]])

In [89]:
arr1

array([[1, 3],
       [7, 8]])

In [90]:
arr2

array([[2, 3],
       [4, 5]])

In [91]:
arr1 @ arr2

array([[14, 18],
       [46, 61]])

lets suppose you have 3 algebric equation

7x+5y-3z = 16

3x-5y+2z = -8

5x+3y-7z = 0

we need to find the value of x, y, z by using the linear algebra

In [92]:
a = np.array([[7,5,-3], [3,-5,2], [5,3,-7]])

In [93]:
b = np.array([16, -8, 0])

In [94]:
np.linalg.solve(a ,b)

array([1., 3., 2.])

In [95]:
## on LHS matrix a and RHS matrtix b

In [96]:
arr1

array([[1, 3],
       [7, 8]])

In [98]:
np.linalg.det(arr1)

-13.0

# **PANDAS BASIC**