In [1]:
import numpy as np

#  **21st Jan : Numpy Advance**

In [2]:
arr = np.ones((3,4))

In [3]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [5]:
arr * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [6]:
np.empty((3,5))

## it will give some random numbers. don't go upon the term

array([[4.87284105e-310, 0.00000000e+000, 1.14199199e+243,
        4.72883470e+164, 1.96253279e+243],
       [8.56486049e+183, 1.38502015e+219, 1.27826274e-152,
        3.99370559e+252, 2.42766859e-154],
       [5.73818475e+180, 4.03259187e+175, 6.77100927e-043,
                    nan, 1.26480805e-321]])

In [7]:
np.empty((3,5), int)

array([[    131942886763856,      98641982469488, 1729676934817844225,
        1729676930523073537, 1010229097596652033],
       [  35747867507036208,   35747867511423103,   35747867511423103,
          35747867511423103,  323977702795052159],
       [  35747867503170131,   35747867511423103,   12680113560682623,
                          0,                 128]])

In [8]:
## if we don't use the integer then we can get the float values.

In [9]:
## np.eye is a diagonal matrix which return 1 at diagonals and 0 elsewhere

## it will give you the square matrix, means a 2D matrix (length breadth equal)

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
## converting into integer

np.eye(4, dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [11]:
## sometimes we need to generate a matrix where these comes in handy.

##### Converting Array into a Dataframe

In [12]:
import pandas as pd

In [13]:
# let suppose you have an array (here arr), now you want to put/convert in a dataframe, there pandas comes

pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

##### Extra Topics

In [14]:
import random

In [15]:
random.choice((1,2,3,4,5,6)) ## it provide any random value from 1 to 5. can be used for making ludo game

2

In [16]:
## another part from random

random.choice('Ajay') ## gives any letter from the name ''Ajay

'A'

In [17]:
## another

random.randrange(1,1000)

523

In [18]:
random.random() ## a random number is generated between 0 (included), 1 (excluded)

0.43559045988855083

In [19]:
l1 = [1,2,3,4,5]

random.shuffle(l1)

In [20]:
l1

[1, 2, 4, 3, 5]

In [21]:
## we can generate a random number distribution (a number between 7 and 14)

random.uniform(7,14)

9.195223118752473

**Same thing can be done by numpy as well**

In [22]:
## generate an array using random

np.random.rand(2,3)

array([[0.48830239, 0.65503259, 0.8171906 ],
       [0.55728729, 0.62897039, 0.93065311]])

In [23]:
np.random.rand(1)

array([0.22256762])

In [24]:
np.random.randn(2,3) ## showing uniform distribution

array([[-0.19364897, -1.21264751,  0.94733194],
       [ 0.94249371, -1.26038363,  2.97347629]])

In [25]:
np.random.random_sample()

## np.random.rand(1) and np.random.random_sample() the same thing. difference is that the 1st one return the value as array

0.8712251123181722

In [26]:
np.random.randint(1,5, size=(3,4))

array([[4, 4, 1, 1],
       [2, 3, 3, 1],
       [2, 4, 1, 1]])

In [27]:
arr = np.random.randint(1,5, size=(3,4))

In [28]:
arr.shape

(3, 4)

In [29]:
arr.size

12

In [30]:
arr.ndim

2

In [31]:
## resizing the array 'arr'

In [32]:
arr.reshape(2,6)

array([[3, 1, 4, 4, 4, 1],
       [4, 1, 4, 2, 1, 1]])

In [33]:
## we need to know that the array size (here 12) cannot be changed

In [34]:
arr.reshape(12,)

array([3, 1, 4, 4, 4, 1, 4, 1, 4, 2, 1, 1])

In [35]:
arr.reshape(12,1)

array([[3],
       [1],
       [4],
       [4],
       [4],
       [1],
       [4],
       [1],
       [4],
       [2],
       [1],
       [1]])

In [36]:
arr.reshape(4,-1) ## it will internally figure it out

array([[3, 1, 4],
       [4, 4, 1],
       [4, 1, 4],
       [2, 1, 1]])

In [37]:
arr.reshape(3,-1)

array([[3, 1, 4, 4],
       [4, 1, 4, 1],
       [4, 2, 1, 1]])

In [38]:
arr.reshape(-1,4)

array([[3, 1, 4, 4],
       [4, 1, 4, 1],
       [4, 2, 1, 1]])

In [39]:
arr.reshape(3,4).base ## it will pointing out what is the original array

array([[3, 1, 4, 4],
       [4, 1, 4, 1],
       [4, 2, 1, 1]])

In [40]:
arr.reshape(2,2,3)

array([[[3, 1, 4],
        [4, 4, 1]],

       [[4, 1, 4],
        [2, 1, 1]]])

In [41]:
arr.reshape(1,2,2,3)

array([[[[3, 1, 4],
         [4, 4, 1]],

        [[4, 1, 4],
         [2, 1, 1]]]])

In [42]:
arr.reshape(4,3,1)

array([[[3],
        [1],
        [4]],

       [[4],
        [4],
        [1]],

       [[4],
        [1],
        [4]],

       [[2],
        [1],
        [1]]])

In [43]:
l2 = [1,2,3,4]

In [44]:
np.array(l2)

array([1, 2, 3, 4])

In [45]:
arr2 = np.array([[2,3], [4,5]])

In [46]:
arr2

array([[2, 3],
       [4, 5]])

In [47]:
arr3 = np.zeros((3,4))

In [48]:
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
arr4 = np.zeros((1, 3, 4)) ## 3 rows 4 columns becomes 2D array + 1 extra dimension

In [50]:
arr4

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [51]:
## similarly

arr5 = np.zeros((1, 1, 3, 4)) ## 3 rows 4 columns becomes 2D array + 1 extra dimension + 1 extra dimension

In [52]:
arr5

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [53]:
## but if we use 2 in the first position like

arr6 = np.zeros((2, 3, 4))

arr6

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [54]:
## it will repeat the values in the 2nd dimension

In [55]:
arr01 = np.random.randint(1,10, (5,6))

In [56]:
arr01

array([[9, 9, 9, 8, 2, 8],
       [7, 8, 3, 2, 5, 5],
       [9, 7, 9, 1, 2, 1],
       [1, 9, 4, 5, 9, 6],
       [7, 1, 1, 2, 5, 8]])

In [57]:
## finding the values in the array

arr01 > 5

array([[ True,  True,  True,  True, False,  True],
       [ True,  True, False, False, False, False],
       [ True,  True,  True, False, False, False],
       [False,  True, False, False,  True,  True],
       [ True, False, False, False, False,  True]])

***IMPORTANT***

In [58]:
## filtering the values with removing the condition and rest are keeping

arr01[arr01 > 5]

array([9, 9, 9, 8, 8, 7, 8, 9, 7, 9, 9, 9, 6, 7, 8])

In [59]:
arr01[arr01 < 5]

array([2, 3, 2, 1, 2, 1, 1, 4, 1, 1, 2])

In [60]:
### accessing the element

arr01[0]

array([9, 9, 9, 8, 2, 8])

In [61]:
arr01[2]

array([9, 7, 9, 1, 2, 1])

In [62]:
arr01[0][3]

8

In [63]:
arr01[0, [1,3]]

array([9, 8])

In [64]:
arr01[2:4]

array([[9, 7, 9, 1, 2, 1],
       [1, 9, 4, 5, 9, 6]])

In [65]:
arr01[2:4,[0,2]]

array([[9, 9],
       [1, 4]])

In [66]:
arr01[2:5,0:2] ## slicing

array([[9, 7],
       [1, 9],
       [7, 1]])

In [67]:
arr01[2:5, [0,2]] ## will give the 0th row and 2nd row values

array([[9, 9],
       [1, 4],
       [7, 1]])

In [68]:
arr01[[2,4]] ## selecting specific columns

array([[9, 7, 9, 1, 2, 1],
       [7, 1, 1, 2, 5, 8]])

In [69]:


arr1 = np.random.randint(1,10, (3,3))
arr2 = np.random.randint(1,10, (3,3))

arr1

array([[7, 4, 1],
       [2, 3, 3],
       [3, 7, 9]])

In [70]:
arr2

array([[8, 7, 6],
       [3, 8, 7],
       [8, 5, 6]])

In [71]:
## adding two array indexwise

arr1 + arr2

array([[15, 11,  7],
       [ 5, 11, 10],
       [11, 12, 15]])

In [72]:
arr1 - arr2 ## subtracting two array indexwise

array([[-1, -3, -5],
       [-1, -5, -4],
       [-5,  2,  3]])

In [73]:
## matrix multiplication in array

arr1 @ arr2

array([[ 76,  86,  76],
       [ 49,  53,  51],
       [117, 122, 121]])

In [74]:
# dividing two array indexwise

arr1 / arr2

array([[0.875     , 0.57142857, 0.16666667],
       [0.66666667, 0.375     , 0.42857143],
       [0.375     , 1.4       , 1.5       ]])

***Broadcasting***

In [75]:
## broadcasting with array means doing the same thing with every element of the array

# for example

arr3 = np.zeros((3,4))

In [76]:
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
arr3 + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [78]:
## but

a = np.array([1,2,3,4])

In [79]:
a

array([1, 2, 3, 4])

In [80]:
arr3 + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [81]:
## adding row wise

b = np.array([1,2,3])

In [82]:
b

array([1, 2, 3])

In [83]:
# making 2D
b = np.array([[1,2,3]])

In [84]:
b

array([[1, 2, 3]])

In [85]:
b.T ## transposing

array([[1],
       [2],
       [3]])

In [86]:
arr3 + b.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [87]:
c = np.array([1,2,3])



In [88]:
c

array([1, 2, 3])

In [89]:
c.T

array([1, 2, 3])

In [90]:
np.sqrt(c)

array([1.        , 1.41421356, 1.73205081])

In [91]:
np.log10(c)

array([0.        , 0.30103   , 0.47712125])

In [92]:
np.exp(c)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [93]:
np.min(c)

1

In [94]:
np.max(c)

3

In [95]:
a

array([1, 2, 3, 4])

In [96]:
np.min(a)

1

In [97]:
arr1

array([[7, 4, 1],
       [2, 3, 3],
       [3, 7, 9]])

In [98]:
np.min(arr1)

1

In [99]:
## Transposing the array

In [100]:
arr1.T

array([[7, 2, 3],
       [4, 3, 7],
       [1, 3, 9]])

In [103]:
arr1.flatten() ## reduce higher dimension to one dimension

array([7, 4, 1, 2, 3, 3, 3, 7, 9])

In [104]:
### expand dims >> expands the array by intersecting a new axis

arr = np.array([[1,2,3],[4,5,6]])



In [105]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
np.sum

<function sum at 0x7800533ddcf0>

In [108]:
## sum only column wise (but calculate column wise)

np.sum(arr, axis=1)

array([ 6, 15])

In [109]:
## sum only row wise (but calculates row wise)

np.sum(arr, axis=0)

array([5, 7, 9])

In [110]:
## expand_dims >> expend the dimension of array

arr = np.array([1,2,3,4])

arr

array([1, 2, 3, 4])

In [111]:
arr.ndim

1

In [112]:
arr_1 = np.expand_dims(arr, axis=0)

arr_1

array([[1, 2, 3, 4]])

In [113]:
arr_1.ndim

2

In [115]:
np.expand_dims(arr, axis=1)

array([[1],
       [2],
       [3],
       [4]])